# Checklists

by Jade Benjamin-Chung 

## Pre-analysis plan checklist

Before registering a pre-analysis plan, verify that it includes all elements described in the [Write and register pre-analysis plans](reproducibility.html#write-and-register-pre-analysis-plans) section. See the following pre-analysis plans for examples from our lab:

- [Trials of water, sanitation, and hygiene interventions](https://osf.io/tprw2/)
- [Observational study of school-located influenza vaccination](https://osf.io/c8xuq/)
- [Re-analysis of malaria intervention trial](https://osf.io/rb3cw/)


## Code checklist
- Does the script run without errors?
- Is code self-contained within repo and/or associated Box folder?
- Is all commented out code / remarks removed? 
- Does the header accurately describe the process completed in the script? 
- Are file paths relative (using `here()`) rather than absolute?
- Are assertions present after merges, filters, and key variable creation steps?
- Do unit tests pass (`testthat::test_dir('9-tests')`)?
- Are random seeds set where relevant?
- Is the script pushed to its github repository?
- Does the code adhere to the [coding style guide](https://jadebc.github.io/lab-manual/coding-style.html)? 
- Are all warnings ignorable? Should any warnings be intentionally suppressed or addressed?


## Manuscript checklist
*This is adapted in part from [this article](https://www.nature.com/articles/d41586-019-01431-z).*

- Have you completed the relevant reporting checklist, if applicable? ([Collection of checklists](https://www.equator-network.org/about-us/what-is-a-reporting-guideline/))
- Are the study results within the manuscript replicable (i.e., if you rerun the code in the study's repository, the tables and figures will be exactly replicated?)
- Is a target journal selected?
- Is the title declarative, in other words, does it state the object/findings rather than suggest them?
- Is the word count of the manuscript close to the target journal's allowance?
- Does the manuscript adhere to the formatting guide of the target journal?
- Does the manuscript use a consistent voice (passive or active -- usually active is preferred ... pun intended)?
- Is each figure and table (including supplementary material) referenced in the main text?
- Is there a caption for each figure and table (including supplementary material)?  
- Are all numbers in the text (sample sizes, point estimates, CIs, p-values) generated programmatically from the analysis output rather than manually typed?  
- Are tables/figures and supplementary material numbered in accordance with their appearance in the main text? 
- Does the text use past tense if it is reporting research findings or future tense if it is a study protocol? 
- Does the text avoid subjective wording (e.g., "interesting", "dramatic")?
- Does the text use minimal abbreviations, and are all abbreviations defined at first use?
- Does the text avoid directionless words? (e.g., instead of writing, ‘Precipitation influences disease risk’, write, ‘Precipitation was associated with increased disease risk’). 
- Does the text avoid making causal claims that are not supported by the study design? Be careful about the words "effect", "increase", and "decrease", which are often interpreted as causal. 
- Does the text avoid describing results with the word "significant", which can easily be confused with statistical significance? (see references on this topic [here](https://journals.lww.com/epidem/Fulltext/2001/05000/The_Value_of_P.2.aspx))
- Have you drafted author contributions? Do they follow the [CRediT Taxonomy](https://journals.plos.org/plosone/s/authorship/?utm_source=plos&utm_medium=blog&utm_campaign=plos-1607-credit#loc-author-contributions) for author contributions?

## Figure checklist
- Are the x-axis and y-axis labeled?
- Are the axis limits appropriate (e.g., not truncating data or exaggerating differences)?
- If the figure includes panels, is each panel labeled?
- Are there sufficient numerical / text labels and breaks on the x-axis and y-axis? 
- Is the font size appropriate (i.e., large enough to read, not so large that it distracts from the data presented in the figure?)
- Are the colors used colorblind friendly? See a colorblind-friendly palette [here](http://www.cookbook-r.com/Graphs/Colors_(ggplot2)/#a-colorblind-friendly-palette), a neat palette generator with colorblind options [here](https://medialab.github.io/iwanthue/?utm_source=Nature+Briefing&utm_campaign=2c68711076-briefing-dy-20211006&utm_medium=email&utm_term=0_c9dfd39373-2c68711076-44335685), and an article on why this matters [here](https://www.nature.com/articles/d41586-021-02696-z)
- Are colors/shapes/line types defined in a legend?
- Are the legends and other labels easy to understand with minimal abbreviations? 
- If there is overplotting, is transparency used to show overlapping data? 
- Are 95% confidence intervals or other measures of precision shown, if applicable?
- Does the figure have a consistent theme/style with other figures in the manuscript?
