# Resources

by Jade Benjamin-Chung and Kunal Mishra

## Resources for R

- [dplyr and tidyr cheat sheet](https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf)
- [ggplot cheat sheet](https://www.rstudio.com/wp-content/uploads/2015/03/ggplot2-cheatsheet.pdf)
- [data table cheat sheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/datatable_Cheat_Sheet_R.pdf)
- [RMarkdown cheat sheet](https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf)
- [Hadley Wickham's R Style Guide](http://adv-r.had.co.nz/Style.html)
- [Jade's R-for-epi course](https://ucb-epi-r.github.io)
- [Tidy Eval in 5 Minutes](https://www.youtube.com/watch?v=nERXS3ssntw) (video)
- [Tidy Evaluation](https://tidyeval.tidyverse.org/index.html) (e-book)
- [Data Frame Columns as Arguments to Dplyr Functions](https://www.brodrigues.co/blog/2016-07-18-data-frame-columns-as-arguments-to-dplyr-functions/) (blog)
- [Standard Evaluation for *_join](https://stackoverflow.com/questions/28125816/r-standard-evaluation-for-join-dplyr) (stackoverflow)
- [Programming with dplyr](https://dplyr.tidyverse.org/articles/programming.html) (package vignette)

## Resources for Git & Github
- [Data Camp introduction to Git](https://www.datacamp.com/courses/introduction-to-git-for-data-science)
- [Introduction to Github](https://lab.github.com/githubtraining/introduction-to-github)

## Scientific figures
- [Ten Simple Rules for Better Figures](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003833)

## Writing

- [Tips on how to write a great science paper](https://www.nature.com/articles/d41586-019-02918-5)
- [ICMJE Definition of authorship](http://www.icmje.org/recommendations/browse/roles-and-responsibilities/defining-the-role-of-authors-and-contributors.html)
- [Nature article on elements of style for scientific writing](https://www.nature.com/articles/nphys724)
- [The Pathway to Publishing: A Guide to Quantitative Writing in the Health Sciences ](https://link.springer.com/book/10.1007/978-3-030-98175-4)
- [Secret, actionable writing tips](https://x.com/acagamic/status/1680381737816424450)

## Presentations

- [How to tell a compelling story in scientific presentations](https://www.nature.com/articles/d41586-021-03603-2)
- [How to give a killer narratively-driven scientific talk](https://www-sciencedirect-com.stanford.idm.oclc.org/science/article/pii/S1471491423000928)
- [How to make a better poster](https://www.youtube.com/watch?v=1RwJbhkCA58&t=1171s)
- [How to make an even better poster](https://mitcommlab.mit.edu/be/2023/09/27/toward-an-evenbetterposter-improving-the-betterposter-template/)

## Professional advice
- [Professional advice, especially for your first job](https://docs.google.com/document/d/1ckgRCcr7FFPyymyMA6Y_-cB_vftOyrrxT28c6gRg0PI/edit)

## Funding
- [Building Your Funding Train](https://grantwriting.stanford.edu/funding-train/#ep)

## Ethics and global health research
- [Global Code of Conduct For Research in Resource-Poor Settings](https://www.globalcodeofconduct.org/wp-content/uploads/2018/05/Global-Code-of-Conduct-Brochure.pdf)
- [Who is a global health expert? Advice for aspiring global health experts](https://journals.plos.org/globalpublichealth/article?id=10.1371/journal.pgph.0002269)
- [Transforming Global Health Partnerships](https://link.springer.com/book/9783031537929)
